name: Issue after discussion
description: Report a confirmed issue after a Discussion has been created.
title: "[Issue]: "
body:
  - type: input
    id: discussion_url
    attributes:
      label: Discussion URL
      description: Link the Discussion where this was first discussed.
      placeholder: https://github.com/MiguelElGallo/SnowflakeCortexCLI/discussions/...
    validations:
      required: true
  - type: textarea
    id: problem
    attributes:
      label: Problem summary
      description: What is the issue that needs to be solved?
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
    validations:
      required: true
